# render.yaml
services:
  - type: web
    name: novamed-backend
    runtime: node
    buildCommand: npm install
    startCommand: node app/index.js
    envVars:
      - key: BREVO_SMTP_USER
        sync: false
      - key: BREVO_SMTP_PASS
        sync: false
      - key: FAST2SMS_KEY
        sync: false
      - key: HOSPITAL_EMAIL
        sync: false
      - key: HOSPITAL_PHONE
        sync: false